#############################################################################
# Makefile for building: RS485Control.app/Contents/MacOS/RS485Control
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  RS485Control.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile RS485Control.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -Ibuild/moc -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.19/lib
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RS485Control1.0.0
DISTDIR = /Users/han24-m5air/gitw/hy1500-1/build/obj/RS485Control1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt@5/5.15.19/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtSerialPort -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/controlalgorithm.cpp \
		src/appui.cpp \
		src/applogic.cpp \
		src/rs485device.cpp build/moc/moc_appui.cpp \
		build/moc/moc_applogic.cpp \
		build/moc/moc_rs485device.cpp
OBJECTS       = build/obj/main.o \
		build/obj/controlalgorithm.o \
		build/obj/appui.o \
		build/obj/applogic.o \
		build/obj/rs485device.o \
		build/obj/moc_appui.o \
		build/obj/moc_applogic.o \
		build/obj/moc_rs485device.o
DIST          = /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/lex.prf \
		RS485Control.pro src/controlalgorithm.h \
		src/appui.h \
		src/applogic.h \
		src/rs485device.h src/main.cpp \
		src/controlalgorithm.cpp \
		src/appui.cpp \
		src/applogic.cpp \
		src/rs485device.cpp
QMAKE_TARGET  = RS485Control
DESTDIR       = 
TARGET        = RS485Control.app/Contents/MacOS/RS485Control

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 26.5
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/han24-m5air/gitw/hy1500-1/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/han24-m5air/gitw/hy1500-1/RS485Control.pro


include /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

RS485Control.app/Contents/MacOS/RS485Control:  $(OBJECTS)  
	@test -d RS485Control.app/Contents/MacOS/ || mkdir -p RS485Control.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RS485Control.pro /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/lex.prf \
		RS485Control.pro \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Resources/QtSerialPort.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile RS485Control.pro
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/lex.prf:
RS485Control.pro:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Resources/QtSerialPort.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile RS485Control.pro

qmake_all: FORCE

RS485Control.app/Contents/PkgInfo: 
	@test -d RS485Control.app/Contents || mkdir -p RS485Control.app/Contents
	@$(DEL_FILE) RS485Control.app/Contents/PkgInfo
	@echo "APPL????" > RS485Control.app/Contents/PkgInfo
RS485Control.app/Contents/Resources/empty.lproj: 
	@test -d RS485Control.app/Contents/Resources || mkdir -p RS485Control.app/Contents/Resources
	@touch RS485Control.app/Contents/Resources/empty.lproj
	
RS485Control.app/Contents/Info.plist: 
	@test -d RS485Control.app/Contents || mkdir -p RS485Control.app/Contents
	@$(DEL_FILE) RS485Control.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.RS485Control,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.RS485Control,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,RS485Control,g" -e "s,@LIBRARY@,RS485Control,g" -e "s,\$${EXECUTABLE_NAME},RS485Control,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/Info.plist.app >RS485Control.app/Contents/Info.plist

all: Makefile \
		RS485Control.app/Contents/PkgInfo \
		RS485Control.app/Contents/Resources/empty.lproj \
		RS485Control.app/Contents/Info.plist RS485Control.app/Contents/MacOS/RS485Control

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/controlalgorithm.h src/appui.h src/applogic.h src/rs485device.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/controlalgorithm.cpp src/appui.cpp src/applogic.cpp src/rs485device.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r RS485Control.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o build/moc/moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_appui.cpp build/moc/moc_applogic.cpp build/moc/moc_rs485device.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_appui.cpp build/moc/moc_applogic.cpp build/moc/moc_rs485device.cpp
build/moc/moc_appui.cpp: src/appui.h \
		src/applogic.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QHash \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qhash.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QThread \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDate \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		src/controlalgorithm.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QStringList \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstringlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QPoint \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QSet \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qset.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		build/moc/moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/han24-m5air/gitw/hy1500-1/build/moc/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/han24-m5air/gitw/hy1500-1 -I/Users/han24-m5air/gitw/hy1500-1/src -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/21/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib src/appui.h -o build/moc/moc_appui.cpp

build/moc/moc_applogic.cpp: src/applogic.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QHash \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qhash.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QThread \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDate \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		build/moc/moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/han24-m5air/gitw/hy1500-1/build/moc/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/han24-m5air/gitw/hy1500-1 -I/Users/han24-m5air/gitw/hy1500-1/src -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/21/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib src/applogic.h -o build/moc/moc_applogic.cpp

build/moc/moc_rs485device.cpp: src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		build/moc/moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/han24-m5air/gitw/hy1500-1/build/moc/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/han24-m5air/gitw/hy1500-1 -I/Users/han24-m5air/gitw/hy1500-1/src -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/21/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib src/rs485device.h -o build/moc/moc_rs485device.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp src/appui.h \
		src/applogic.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QHash \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qhash.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QThread \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDate \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		src/controlalgorithm.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QStringList \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstringlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QPoint \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QSet \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qset.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFileInfo \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfileinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/controlalgorithm.o: src/controlalgorithm.cpp src/controlalgorithm.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QStringList \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstringlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QtGlobal \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qglobal.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/controlalgorithm.o src/controlalgorithm.cpp

build/obj/appui.o: src/appui.cpp src/appui.h \
		src/applogic.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QHash \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qhash.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QThread \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDate \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		src/controlalgorithm.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QStringList \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstringlist.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QFrame \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qframe.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QPoint \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QSet \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qset.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QAbstractSpinBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QAbstractItemView \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QComboBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcombobox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDateEdit \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qspinbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QFontMetrics \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qfontmetrics.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QGridLayout \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QHeaderView \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qheaderview.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMessageBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QMouseEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainterPath \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainterpath.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPalette \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpalette.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QScrollBar \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QScrollArea \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QSettings \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QSignalBlocker \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QSpinBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QStackedWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QStyledItemDelegate \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QStyle \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qstyle.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QTableWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/appui.o src/appui.cpp

build/obj/applogic.o: src/applogic.cpp src/applogic.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QHash \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qhash.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QThread \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDate \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFile \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTextStream \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtextstream.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QSettings \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QFileInfo \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfileinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMetaObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobjectdefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QStorageInfo \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstorageinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/applogic.o src/applogic.cpp

build/obj/rs485device.o: src/rs485device.cpp src/rs485device.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QString \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qstring.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMap \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmap.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVariant \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvariant.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDateTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QByteArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qbytearray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QVector \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qvector.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QQueue \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qqueue.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QMutex \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qmutex.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QThread \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDebug \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/rs485device.o src/rs485device.cpp

build/obj/moc_appui.o: build/moc/moc_appui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_appui.o build/moc/moc_appui.cpp

build/obj/moc_applogic.o: build/moc/moc_applogic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_applogic.o build/moc/moc_applogic.cpp

build/obj/moc_rs485device.o: build/moc/moc_rs485device.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_rs485device.o build/moc/moc_rs485device.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

