#!/usr/bin/env bash
set -euo pipefail

# Android APK build script for RS485Launcher
# Prerequisites: Android build-tools 34, platform-33, JDK 17, Qt 5.15 for Android

APP_NAME="RS485Launcher"
PACKAGE_NAME="com.rs485.launcher"
KEYSTORE="android/rs485.keystore"
ALIAS="rs485"
QT_ANDROID_ROOT="${QT_ANDROID_ROOT:-/opt/Qt/5.15.2/android_arm64_v8a}"
ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}"

if [ ! -d "$QT_ANDROID_ROOT" ]; then
  echo "Qt Android root not found: $QT_ANDROID_ROOT"
  echo "Set QT_ANDROID_ROOT to your Qt 5.15 Android arm64-v8a installation."
  exit 1
fi

export PATH="$QT_ANDROID_ROOT/bin:$PATH"
export ANDROID_SDK_ROOT
export JAVA_HOME="${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk-amd64}"

mkdir -p android/dist

# 1. Build native binary via qmake
cd android/src
qmake "ANDROID_ABIS=arm64-v8a" "ANDROID_TARGET_SDK=33" "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" RS485Control.pro
make -j4

# 2. Deploy Qt libraries + manifest
androiddeployqt \
  --input android-libRS485Control.so-deployment-settings.json \
  --output ../build/outputs/apk/debug \
  --android-platform android-33 \
  --jdk "$JAVA_HOME" \
  --gradle

# 3. Build debug APK with Gradle (generated by androiddeployqt)
cd ../
chmod +x gradlew || true
if [ -f gradlew ]; then
  ./gradlew assembleDebug
else
  echo "gradlew not found; androiddeployqt should have generated the Gradle project."
  ls -R build/outputs/apk/debug || true
  exit 1
fi

# 4. Copy artifact
cp build/outputs/apk/debug/*.apk dist/RS485Launcher-debug.apk || true
if [ ! -f dist/RS485Launcher-debug.apk ]; then
  echo "APK build failed"
  exit 1
fi

echo "APK built at android/dist/RS485Launcher-debug.apk"
